// Copyright (c) ppy Pty Ltd <contact@ppy.sh>. Licensed under the MIT Licence.
// See the LICENCE file in the repository root for full licence text.

using osu.Framework.Graphics.Primitives;

namespace osu.Framework.Text
{
    /// <summary>
    /// Describes a character generated by <see cref="TextBuilder"/>.
    /// </summary>
    public class CharacterInfo
    {
        /// <summary>
        /// The glyph which this character represents.
        /// </summary>
        public ICharacterGlyph Glyph;

        /// <summary>
        /// The rectangle for the character to be drawn in.
        /// </summary>
        public RectangleF DrawRectangle;

        /// <summary>
        /// Whether this is the first character on a new line.
        /// </summary>
        public bool OnNewLine;
    }
}
